#!/usr/bin/env node
/**
 * Turns the sevDesk OpenAPI document into a compact, searchable operation
 * catalogue that the server ships with. Doing this at build time keeps the
 * 660 KB spec out of the runtime and makes every operation discoverable
 * through three generic tools instead of 151 individual ones.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const SPEC = join(root, "openapi", "sevdesk-openapi.yaml");
const OUT = join(root, "src", "generated", "catalog.ts");

const METHODS = ["get", "post", "put", "delete", "patch"];

/** Resolve a local $ref one level; sevDesk's spec only uses component refs. */
function deref(spec, node, depth = 0) {
  if (!node || typeof node !== "object" || depth > 6) return node;
  if (node.$ref && typeof node.$ref === "string") {
    const path = node.$ref.replace(/^#\//, "").split("/");
    let cur = spec;
    for (const p of path) cur = cur?.[p];
    return deref(spec, cur, depth + 1);
  }
  return node;
}

/** Collapse a JSON-Schema-ish node into a short human description. */
function summariseSchema(spec, schema, depth = 0) {
  const s = deref(spec, schema, 0);
  if (!s || typeof s !== "object") return "any";
  if (s.enum) return `${s.type ?? "string"} (${s.enum.join(" | ")})`;
  if (s.type === "array") {
    return depth > 2 ? "array" : `array<${summariseSchema(spec, s.items, depth + 1)}>`;
  }
  if (s.type === "object" || s.properties) {
    if (depth > 1) return "object";
    const props = Object.entries(s.properties ?? {})
      .slice(0, 12)
      .map(([k, v]) => `${k}: ${summariseSchema(spec, v, depth + 1)}`);
    return props.length ? `{ ${props.join(", ")} }` : "object";
  }
  return s.type ?? "any";
}

function firstLine(text, max = 200) {
  if (!text) return "";
  const clean = String(text)
    .replace(/<br\s*\/?>/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
  return clean.length > max ? clean.slice(0, max - 1) + "…" : clean;
}

const spec = parse(readFileSync(SPEC, "utf8"));
const operations = [];

for (const [path, item] of Object.entries(spec.paths ?? {})) {
  const shared = item.parameters ?? [];
  for (const method of METHODS) {
    const op = item[method];
    if (!op) continue;

    const params = [...shared, ...(op.parameters ?? [])].map((raw) => {
      const p = deref(spec, raw);
      return {
        name: p.name,
        in: p.in,
        required: Boolean(p.required),
        type: summariseSchema(spec, p.schema),
        description: firstLine(p.description, 160),
      };
    });

    let body;
    const rb = deref(spec, op.requestBody);
    if (rb?.content) {
      const [mime, media] = Object.entries(rb.content)[0] ?? [];
      body = {
        mime,
        required: Boolean(rb.required),
        schema: summariseSchema(spec, media?.schema),
      };
    }

    const operationId =
      op.operationId ||
      `${method}${path.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())}`;

    operations.push({
      operationId,
      method: method.toUpperCase(),
      path,
      tags: op.tags ?? [],
      summary: firstLine(op.summary, 160),
      description: firstLine(op.description, 400),
      params,
      body,
      // Anything that is not a GET can change data in the customer's books.
      mutating: method !== "get",
    });
  }
}

operations.sort((a, b) => a.operationId.localeCompare(b.operationId));

const catalog = {
  apiTitle: spec.info?.title ?? "sevDesk API",
  apiVersion: spec.info?.version ?? "unknown",
  baseUrl: spec.servers?.[0]?.url ?? "https://my.sevdesk.de/api/v1",
  generatedFrom: "openapi/sevdesk-openapi.yaml",
  operationCount: operations.length,
  tags: [...new Set(operations.flatMap((o) => o.tags))].sort(),
  operations,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  "// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.\n" +
    'import type { Catalog } from "../lib/catalog-types.js";\n\n' +
    "export const catalog: Catalog = " +
    JSON.stringify(catalog, null, 1) +
    ";\n",
);

const mutating = operations.filter((o) => o.mutating).length;
console.log(
  `catalog: ${operations.length} operations (${operations.length - mutating} read, ${mutating} mutating) ` +
    `across ${catalog.tags.length} tags -> ${OUT}`,
);
